import os
from dotenv import load_dotenv

load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL")

SCALEKIT_ENVIRONMENT_URL = os.getenv("SCALEKIT_ENVIRONMENT_URL")
SCALEKIT_CLIENT_ID = os.getenv("SCALEKIT_CLIENT_ID")
SCALEKIT_CLIENT_SECRET = os.getenv("SCALEKIT_CLIENT_SECRET")
SCALEKIT_RESOURCE_ID = os.getenv("SCALEKIT_RESOURCE_ID")

MCP_RESOURCE_URL = os.getenv("MCP_RESOURCE_URL", "http://localhost:9000/mcp")

AUTHORIZATION_SERVER = f"{SCALEKIT_ENVIRONMENT_URL}/resources/{SCALEKIT_RESOURCE_ID}"
USERINFO_ENDPOINT = f"{AUTHORIZATION_SERVER}/userinfo"